# Generated by Django 4.1.8 on 2023-04-25 19:09

import datetime
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("spendr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expenses",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("added_by", models.CharField(max_length=25)),
                ("date_added", models.DateField(default=datetime.date(2023, 4, 25))),
                ("item_name", models.CharField(max_length=255)),
                ("item_price", models.PositiveIntegerField()),
                ("item_quantity", models.PositiveIntegerField(default=1)),
                ("total_price", models.PositiveIntegerField()),
                ("unique_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="contributions",
            name="contribution_date",
            field=models.DateField(null=True),
        ),
    ]
