# Generated by Django 4.1.8 on 2023-04-26 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spendr", "0002_expenses_alter_contributions_contribution_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="date_added",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
